### PR TITLE
Include <functional> in Demangle.h

### PR DESCRIPTION
**Pull request by etbrady**
This resolves a build error when using Bazel to build on Xcode 15.3

```
In file included from external/swift-index-store~/Sources/CSwiftDemangle/CSwiftDemangle.cpp:1:
external/swift-index-store~/Sources/CSwiftDemangle/PrivateHeaders/include/swift/Demangling/Demangle.h:61:8: error: no template named 'function' in namespace 'std'
  std::function<std::string(uint64_t, uint64_t)> GenericParameterName =
  ~~~~~^
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
```

### CODE REVIEW

**Review by keith — APPROVED** [review]
cool thanks, we should probably re-sync these headers since they're copied from upstream, but doesn't hurt to patch in the meantime to  unblock!
